app/models/bank.rb, app/models/collection.rb, app/models/collection_recyclable.rb, app/models/order.rb, app/models/order_recyclable.rb, app/models/review.rb, app/models/user.rb, db/migrate/20190813050350_rename_orders_to_collections.rb, db/migrate/20190813051623_rename_order_recyclables_to_collection_recyclables.rb, db/migrate/20190813053200_change_foreign_keyfor_reviews.rb, db/migrate/20190813053936_change_foreign_keyfor_collection_recyclables.rb, db/schema.rb
change foreign keys in reviews and collection_recylables from order_id to collection_id
=> Foreignkeys

db/migrate/20190813094614_add_business_to_users.rb, db/schema.rb
Will have to update the Sign Up View Page to add the parameter 'business'
=> migration to add column business boolean in Users

app/controllers/banks_controller.rb, app/views/banks/create.html.erb, app/views/banks/destroy.html.erb, app/views/banks/new.html.erb, app/views/banks/update.html.erb
- The only way to create a Bank is if you have the current_user.id
=> Added the current user when creating Banks

db/seeds.rb
=> removed line in seeds

app/controllers/banks_controller.rb
- required params for bank - additional attributes
=> updated the banks controller required params

app/controllers/pages_controller.rb, app/models/bank.rb, config/routes.rb, db/seeds.rb
- made minor changes to the seeds file so we only are taking the first 10 created banks (this is to limit the Google Maps API Geocoding)
- removed `optional: true` from `bank.rb` (not needed because of our seeds)
=> Seed testing

app/controllers/pages_controller.rb, app/views/pages/help.html.erb, config/routes.rb
- added the help page `views/pages/help.html.erb` (users do not have to be logged in to access this page)
- added the #help method in Pages controller (in case we need it)
=> Custom route: help page

app/controllers/banks_controller.rb, app/javascript/plugins/init_autocomplete.js, app/views/pages/home.html.erb
* fixed the form on home page to add a get method and link to banks/index page upon submission
* updated index in banks controller to take in params[:query] as an argument
=> amended the form on home page to make it a get request to banks index

.github/PULL_REQUEST_TEMPLATE.md
- minor change to pull request template
=> fixed type in pr template

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_footer.scss, app/assets/stylesheets/pages/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
- added some sticky footers
- have to work out the links for the qr and the search
-
=> footers done

app/controllers/collections_controller.rb, app/views/collections/create.html.erb, app/views/collections/index.html.erb, app/views/users/dashboard.html.erb
- changes to collections views, dashboard, and collections controller to check for business account
=> Collections views, dashboard, and Collections Controller changes

app/assets/stylesheets/components/_map.scss, app/views/banks/show.html.erb
- aligned text to the left on the map pop-up card
- added HTML structure for Bank#show (map without coordinate) 
- need to incorporate coordinates relating to instance of the specific Show page
=> Minor changes

app/controllers/banks_controller.rb
- reverted change for conditional statement for empty query
=> Empty query in Bank index

app/views/banks/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
- added flexbox elements to footer in order to space them evenly
- adjusted the height of the map on the index page to ensure the footer is not sat on top of the map
- removed redundant template code from the navbar
=> Navbar  & footer adjustments

app/controllers/banks_controller.rb, app/javascript/packs/map.js, app/javascript/plugins/init_map.js, app/javascript/plugins/init_mapbox.js, app/models/bank.rb, app/views/banks/_map_info_window.html.erb, app/views/banks/edit.html.erb, app/views/banks/new.html.erb, app/views/banks/show.html.erb
- added validations for bank model
- changes to bank controller  in order to set current_user and access current bank.id from #show
- mapbox for bank show implemented, but without the coordinates
=> Bank Controller, View, and Mapbox

app/views/pages/home.html.erb
- changed search button on home from text to an icon
=> fixed search icon in home page

app/views/verifications/show.html.erb
=> changes to qr code to view

app/models/collection.rb
- commented out validation for now
=> commented our validation for now

app/controllers/banks_controller.rb, app/views/banks/show.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb
- made a new review form partial
- displayed reviews for each bank on their show page
- added new variable to banks controller to store the bank reviews
(once we have user id in collections we can also display in the bank show page the username of the user who left the review)
=> added new review form, displayed reviews on the bank show pages

app/views/users/dashboard.html.erb
- made some minor changes to the elements on the Dashboard
=> Dashboard changes

app/controllers/verifications_controller.rb, app/models/collected_plastic.rb, app/models/collection.rb, app/views/verifications/new.html.erb, db/migrate/20190819044659_add_verification_to_collections.rb, db/migrate/20190819045705_create_collected_plastics.rb, db/schema.rb, test/models/collected_plastic_test.rb
- changed to the schema by adding the join table "collected_plastics" and added foreign key 'verification_id' to Collections table
=> Updated schema

Gemfile, Gemfile.lock, app/controllers/banks_controller.rb, app/javascript/plugins/init_mapbox.js, app/models/user.rb, app/uploaders/photo_uploader.rb, app/views/banks/show.html.erb, app/views/users/dashboard.html.erb, db/migrate/20190819094343_add_photo_to_users.rb, db/schema.rb, db/seeds.rb
- added cloudinary and carrierwave gems
- added model associations for carrierwave
- displayed username in the dashboard
- fixed seed file to link plastic names to each bank
- added functions in the mapbox javascript file to show the marker for each bank on the bank show page
=> Showmarkers

app/views/users/dashboard.html.erb, db/seeds.rb
- started changes on seed file - so that Verifications and Collections can have the same information based on id's
- made changes to the dashboard
=> Seed verifications fix

db/migrate/20190820030809_add_collection_to_verifications.rb, db/schema.rb
- updated schema with migration to add collection_id to the verifications table
=> Migration to add foreign key for Verifications table

app/models/collection.rb, db/migrate/20190820030809_add_collection_to_verifications.rb, db/schema.rb, db/seeds.rb
- modifications to fix the seed file and updated the Collection model association
=> updated seeds and modified collection model association

db/seeds.rb
=> fixed seed issue

app/assets/stylesheets/pages/_sign_in.scss, app/views/collections/transaction.html.erb, app/views/devise/sessions/new.html.erb
Added the revised sign-in form
-
=> sign-in form done

app/assets/stylesheets/components/_table.scss, app/views/devise/sessions/new.html.erb, app/views/pages/leaderboard.html.erb, app/views/users/dashboard.html.erb
Styling of the verification table.
-
=> Styling of the leadership board

db/seeds.rb
- reverted seed back to original
=> reverted seed back to original

app/models/bank.rb, app/views/banks/_map_info_window.html.erb
- added return nil if !sum to avoid a crash error
=> fixed issues with homepage

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/components/_map.scss, app/models/bank.rb, app/views/banks/_map_info_window.html.erb
=> changes to map cards

app/views/users/dashboard.html.erb
- fixed dashboard ranking not showing
=> fixed dashboard ranking not showing

app/controllers/users_controller.rb
- we can implement the code commented out if we find problems down the line with line 11
=> added comment to users controller regarding not nil issue

app/views/devise/registrations/new.html.erb
- made the banner simon did fit the sign up page
=> changed the sign up page looking like the sign in

app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb
=> Forgot your password

app/views/verifications/show.html.erb
=> removed some elements

app/assets/stylesheets/components/_button.scss, app/controllers/users_controller.rb, app/views/users/dashboard.html.erb
=> Small minor changes to style

app/assets/stylesheets/components/_table.scss, app/views/verifications/show.html.erb
=> Front end changes

Gemfile.lock
- updated the gemfile.lock, upgrading devise the resolve the security alert
=> updated gemfile.lock file to resolve devise security issue
